/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VisualizadorHorarioObjeto.java
 *
 * Created on 30-05-2010, 04:50:43 PM
 */

package jramos.GUI;

/**
 *
 * @author victor
 */
public class VisualizadorHorarioObjeto extends javax.swing.JDialog {

    /** Creates new form VisualizadorHorarioObjeto */
    public VisualizadorHorarioObjeto(java.awt.Frame parent, boolean modal, Object objetoQueVerHorario) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelVisualizadorHorario = new javax.swing.JPanel();
        panelHorario = new javax.swing.JScrollPane();
        horarioMostrado = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        panelCursos = new javax.swing.JScrollPane();
        tablaCursos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        botonCerrarHorario = new javax.swing.JButton();
        labelClaseObjeto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelNombreObjeto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Horario");

        horarioMostrado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1.- 08:00-09:30", null, null, null, null, null, null},
                {"2.- 09:40-11:10", null, null, null, null, null, null},
                {"3.- 11:20-12:50", null, null, null, null, null, null},
                {"4.- 13:50-15:20", null, null, null, null, null, null},
                {"5.- 15:30-17:00", null, null, null, null, null, null},
                {"6.- 17:10-18:40", null, null, null, null, null, null},
                {"7.- 19:00-20:10", null, null, null, null, null, null},
                {"8.- 20:20-22:00", null, null, null, null, null, null},
                {"9.- 22:00-23:00", null, null, null, null, null, null}
            },
            new String [] {
                "Hora", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        panelHorario.setViewportView(horarioMostrado);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabel1.setText("Cursos");

        tablaCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Curso", "Asignatura"
            }
        ));
        panelCursos.setViewportView(tablaCursos);

        jLabel2.setText("Horario de clases ");

        botonCerrarHorario.setText("Cerrar");
        botonCerrarHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarHorarioActionPerformed(evt);
            }
        });

        labelClaseObjeto.setText("tipoObjeto");

        jLabel3.setText(":");

        labelNombreObjeto.setText("nombreObjeto");

        javax.swing.GroupLayout PanelVisualizadorHorarioLayout = new javax.swing.GroupLayout(PanelVisualizadorHorario);
        PanelVisualizadorHorario.setLayout(PanelVisualizadorHorarioLayout);
        PanelVisualizadorHorarioLayout.setHorizontalGroup(
            PanelVisualizadorHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVisualizadorHorarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelVisualizadorHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelVisualizadorHorarioLayout.createSequentialGroup()
                        .addGroup(PanelVisualizadorHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(panelHorario, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
                            .addComponent(panelCursos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
                            .addGroup(PanelVisualizadorHorarioLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelClaseObjeto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelNombreObjeto)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelVisualizadorHorarioLayout.createSequentialGroup()
                        .addComponent(botonCerrarHorario)
                        .addGap(341, 341, 341))))
        );
        PanelVisualizadorHorarioLayout.setVerticalGroup(
            PanelVisualizadorHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVisualizadorHorarioLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(PanelVisualizadorHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelClaseObjeto)
                    .addComponent(jLabel3)
                    .addComponent(labelNombreObjeto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(botonCerrarHorario)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 782, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelVisualizadorHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelVisualizadorHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCerrarHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarHorarioActionPerformed
        //Al presionar el boton "cerrar" hago invisible la ventana
        this.setVisible(false);
    }//GEN-LAST:event_botonCerrarHorarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelVisualizadorHorario;
    private javax.swing.JButton botonCerrarHorario;
    private javax.swing.JTable horarioMostrado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelClaseObjeto;
    private javax.swing.JLabel labelNombreObjeto;
    private javax.swing.JScrollPane panelCursos;
    private javax.swing.JScrollPane panelHorario;
    private javax.swing.JTable tablaCursos;
    // End of variables declaration//GEN-END:variables

}
