/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DialogoConfirmacion.java
 *
 * Created on 06-06-2010, 01:04:02 PM
 */

package jramos;
import jramos.tiposDatos.Carrera;
import jramos.tiposDatos.Curso;
import jramos.tiposDatos.Facultad;
import jramos.tiposDatos.Profesor;

/**
 *
 * @author victor
 */
public class DialogoConfirmacion extends javax.swing.JDialog {

    public static final int BORRA_PROFESOR = 1;
    public static final int BORRA_FACULTAD = 2;
    public static final int BORRA_CARRERA = 3;
    public static final int BORRA_CURSO = 4;
    private int tipoAccion;
    VentanaPrincipal ventanaPadre;
    private Object objetoABorrar;

    /** Creates new form DialogoConfirmacion */
    public DialogoConfirmacion(VentanaPrincipal parent, boolean modal, int tipoAccion, Object objeto) {
        super(parent, modal);
        initComponents();
        this.ventanaPadre = parent;
        this.tipoAccion = tipoAccion;
        this.objetoABorrar = objeto;
        if (tipoAccion == DialogoConfirmacion.BORRA_PROFESOR)
        {       //MENSAJE A MOSTRAR PARA BORRAR UN PROFESOR
                this.labelAccionAConfirmar1.setText("borrar al profesor: ");
                this.labelAccionAConfirmar2.setText(((Profesor)objeto).getNombreProfesor() + " ?");
        }
        if (tipoAccion == DialogoConfirmacion.BORRA_FACULTAD)
        {       //MENSAJE A MOSTRAR PARA BORRAR UNA FACULTAD
                this.labelAccionAConfirmar1.setText("borrar la facultad: ");
                this.labelAccionAConfirmar2.setText(((Facultad)objeto).getNombreFacultad() + " ?");
        }
        if (tipoAccion == DialogoConfirmacion.BORRA_CARRERA)
        {       //MENSAJE A MOSTRAR CUANDO SE BORRAR UNA CARRERA
                this.labelAccionAConfirmar1.setText("borrar la carrera: ");
                this.labelAccionAConfirmar2.setText(((Carrera)objeto).getNombreCarrera() + " ?");
        }
        if (tipoAccion == DialogoConfirmacion.BORRA_CURSO)
        {       //MENSAJE A MOSTRAR CUANDO SE BORRA UN CURSO
                this.labelAccionAConfirmar1.setText("borrar el curso: ");
                this.labelAccionAConfirmar2.setText(((Curso)objeto).getNombreCurso() + " ?");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botonSi = new javax.swing.JButton();
        botonNo = new javax.swing.JButton();
        labelAccionAConfirmar1 = new javax.swing.JLabel();
        labelAccionAConfirmar2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dialogo de confirmación");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabel1.setText("¿Está seguro que desea");

        botonSi.setText("Si");
        botonSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiActionPerformed(evt);
            }
        });

        botonNo.setText("No");
        botonNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNoActionPerformed(evt);
            }
        });

        labelAccionAConfirmar1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelAccionAConfirmar1.setText("primerMensaje");

        labelAccionAConfirmar2.setFont(new java.awt.Font("Dialog", 1, 14));
        labelAccionAConfirmar2.setText("segundoMensaje");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonSi, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 301, Short.MAX_VALUE)
                        .addComponent(botonNo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelAccionAConfirmar1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(labelAccionAConfirmar2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelAccionAConfirmar1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAccionAConfirmar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonNo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonSi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNoActionPerformed
        // Solo cierro el dialogo de confirmacion si se presiona el boton "NO"
        this.setVisible(false);
    }//GEN-LAST:event_botonNoActionPerformed

    private void botonSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiActionPerformed
        //borro un objeto distinto dependiendo de la acción a realizar
        if (this.tipoAccion == DialogoConfirmacion.BORRA_PROFESOR)
        {       //Acciones para borrar un profesor
                this.ventanaPadre.borrarProfesor((Profesor)this.objetoABorrar);
        }
        if (this.tipoAccion == DialogoConfirmacion.BORRA_FACULTAD)
        {       //Acciones para borrar una facultad
                this.ventanaPadre.borrarFacultad((Facultad)this.objetoABorrar);
        }
        if (this.tipoAccion == DialogoConfirmacion.BORRA_CARRERA)
        {       //Acciones para borrar una carrera
                this.ventanaPadre.borrarCarrera((Carrera)this.objetoABorrar);
        }
        if (this.tipoAccion == DialogoConfirmacion.BORRA_CURSO)
        {       //Acciones para borrar un curso
                this.ventanaPadre.borrarCurso((Curso)this.objetoABorrar);
        }
        this.setVisible(false);
    }//GEN-LAST:event_botonSiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonNo;
    private javax.swing.JButton botonSi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelAccionAConfirmar1;
    private javax.swing.JLabel labelAccionAConfirmar2;
    // End of variables declaration//GEN-END:variables

}
