/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DialogoCarreraNueva.java
 *
 * Created on 28-05-2010, 10:07:19 AM
 */

package jramos;

import jramos.tiposDatos.Facultad;
import jramos.tiposDatos.Carrera;
import java.util.ArrayList;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author victor
 */
public class DialogoCarreraNueva extends javax.swing.JDialog {

    private java.awt.Frame ventanaPadre;
    private ManipuladorListas listManager;
    private SpinnerNumberModel modelCantidadSemestres;
    private int nuevaOEdita;
    private Carrera carreraAEditar;

    /** Creates new form DialogoCarreraNueva */
    public DialogoCarreraNueva(java.awt.Frame ventanaPadre, boolean modal, ManipuladorListas listManager, Carrera carreraAEditar, int nuevaOEdita) {
        super(ventanaPadre, modal);
        initComponents();
        this.setLocationRelativeTo(ventanaPadre);
        this.ventanaPadre = ventanaPadre;
        this.listManager = listManager;
        selectorListaFacultades.removeAllItems();
        ArrayList<Facultad> listaFacultades = listManager.getListaFacultades();
        int i, cantidadFacultades = listaFacultades.size();
        for (i = 0; i < cantidadFacultades; i++)
        {       selectorListaFacultades.addItem(listaFacultades.get(i));
        }
        this.modelCantidadSemestres = new SpinnerNumberModel(4, 1, 20, 1);
        this.spinnerCantidadSemestres.setModel(this.modelCantidadSemestres);
        this.nuevaOEdita = nuevaOEdita;
        if (nuevaOEdita == VentanaPrincipal.EDITA)
        {       this.carreraAEditar = carreraAEditar;
                this.setTitle("Dialogo de edición de carrera");
                this.botonAceptaAgregarCarrera.setText("Aplicar cambios");
                this.campoNombreCarreraNueva.setText(carreraAEditar.getNombreCarrera());
                this.textoDescripcionCarrera.setText(carreraAEditar.getDescripcion());
                this.selectorListaFacultades.setSelectedItem(carreraAEditar.getFacultad());
                this.selectorListaFacultades.setEnabled(false);
                this.spinnerCantidadSemestres.setValue(new Integer(carreraAEditar.getIdSemestresArrayList().size()));
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAceptaAgregarCarrera = new javax.swing.JButton();
        botonCancelarAgregarCarrera = new javax.swing.JButton();
        campoNombreCarreraNueva = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        selectorListaFacultades = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        spinnerCantidadSemestres = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoDescripcionCarrera = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar una carrera");
        setName("Agregar una nueva carrera..."); // NOI18N

        botonAceptaAgregarCarrera.setText("Agregar carrera");
        botonAceptaAgregarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptaAgregarCarreraActionPerformed(evt);
            }
        });

        botonCancelarAgregarCarrera.setText("Cancelar");
        botonCancelarAgregarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarAgregarCarreraActionPerformed(evt);
            }
        });

        campoNombreCarreraNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreCarreraNuevaActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre de la carrera: ");

        jLabel2.setText("Facultad:");

        selectorListaFacultades.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Cantidad de semestres: ");

        spinnerCantidadSemestres.setValue(4);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel4.setText("Descripción de la carrera: (Optativo)");

        textoDescripcionCarrera.setColumns(20);
        textoDescripcionCarrera.setRows(5);
        jScrollPane1.setViewportView(textoDescripcionCarrera);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonAceptaAgregarCarrera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonCancelarAgregarCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(79, 79, 79)
                                            .addComponent(spinnerCantidadSemestres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(selectorListaFacultades, 0, 261, Short.MAX_VALUE))
                                    .addComponent(campoNombreCarreraNueva, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNombreCarreraNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(selectorListaFacultades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(spinnerCantidadSemestres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptaAgregarCarrera)
                    .addComponent(botonCancelarAgregarCarrera))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarAgregarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarAgregarCarreraActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_botonCancelarAgregarCarreraActionPerformed

    private void campoNombreCarreraNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreCarreraNuevaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreCarreraNuevaActionPerformed

    private void botonAceptaAgregarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptaAgregarCarreraActionPerformed
        // Accion a realizar cuando se aprieta el boton "agregar carrera"
        //si lo que se ha escrito es nada, entonces no se agrega la carrera
        if (this.campoNombreCarreraNueva.getText().trim().equals(""))
        {       //abro nueva ventana
                DialogoError dialogoError = new DialogoError(ventanaPadre, rootPaneCheckingEnabled, "No hay un nombre de carrera escrito", "Debe escribir un nombre de carrera");
                dialogoError.setVisible(true);
                dialogoError = null;
                return ;
        }
        if (nuevaOEdita == VentanaPrincipal.NUEVA)
        {       //Si ya existe una carrera con el mismo nombre tampoco se agrega.
                ArrayList<Carrera> listaCompletaCarreras = this.listManager.getListaCarreras();
                for (Carrera carrera : listaCompletaCarreras)
                {       if (this.campoNombreCarreraNueva.getText().equals(carrera.getNombreCarrera()))
                        {       //abro nueva ventana de error.
                                DialogoError dialogoError = new DialogoError(ventanaPadre, rootPaneCheckingEnabled, "El nombre de carrera ya existe.", "vuelva a escribir otro nombre para la carrera");
                                dialogoError.setVisible(true);
                                dialogoError = null;
                                return ;
                        }
                }
                this.listManager.agregaCarrera(this.campoNombreCarreraNueva.getText(), (Facultad)selectorListaFacultades.getSelectedItem(), textoDescripcionCarrera.getText(), this.modelCantidadSemestres.getNumber().intValue());
                ((VentanaPrincipal)this.ventanaPadre).actualizaJListListaCarreras();
        }
        //FALTA AQUI!!!
        else
        {       String nuevaDescrip = this.textoDescripcionCarrera.getText();
                String nuevoNombre = this.campoNombreCarreraNueva.getText();
                int nuevaCantidadSemestres = this.modelCantidadSemestres.getNumber().intValue();

                //Si modifico el nombre de la carrera, me aseguro que no hayan otras carreras con el nombre nuevo
                if (!(carreraAEditar.getNombreCarrera().equals(nuevoNombre)))
                {       for (Carrera carrera : this.listManager.getListaCarreras())
                        {       if (carrera.getNombreCarrera().equals(nuevoNombre))
                                {       //abro nueva ventana de error.
                                        DialogoError dialogoError = new DialogoError(ventanaPadre, rootPaneCheckingEnabled, "El nombre de carrera ya existe.", "vuelva a escribir otro nombre para la carrera");
                                        dialogoError.setVisible(true);
                                        dialogoError = null;
                                        return ;
                                }
                        }
                }
                this.listManager.editaCarrera(carreraAEditar, nuevoNombre, nuevaDescrip, nuevaCantidadSemestres);
                ((VentanaPrincipal)this.ventanaPadre).actualizaJListListaCarreras();
                ((VentanaPrincipal)this.ventanaPadre).actualizaJListListaCursos();
        }
        this.setVisible(false);
    }//GEN-LAST:event_botonAceptaAgregarCarreraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptaAgregarCarrera;
    private javax.swing.JButton botonCancelarAgregarCarrera;
    private javax.swing.JTextField campoNombreCarreraNueva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox selectorListaFacultades;
    private javax.swing.JSpinner spinnerCantidadSemestres;
    private javax.swing.JTextArea textoDescripcionCarrera;
    // End of variables declaration//GEN-END:variables

}
