/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentanaPrincipal.java
 *
 * Created on 27-05-2010, 07:57:59 PM
 */

package jramos;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import jramos.tiposDatos.*;
import jramos.capaIO.CapaIOCursos;
import jramos.capaIO.CapaIOProfes;

/**
 *
 * @author victor
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private ManipuladorListas listManager;
    private CapaIOCursos gestorIOCursos;
    private CapaIOProfes gestorIOProfes;
    private DefaultListModel listModelFacultades;
    private DefaultListModel listModelCarreras;
    private DefaultListModel listModelProfesores;
    private DefaultListModel listModelCursos;

    /** Creates new form VentanaPrincipal */
    public VentanaPrincipal(ManipuladorListas listManager, CapaIOCursos gestorIOCursos, CapaIOProfes gestorIOProfes) {
        initComponents();
        int i, tamLista;
        this.listManager = listManager;
        this.visualizadorListaFacultades.removeAll();
        this.visualizadorListaProfes.removeAll();
        this.visualizadorListaCarreras.removeAll();
        this.visualizadorListaCursos.removeAll();
        this.gestorIOCursos = gestorIOCursos;
        this.gestorIOProfes = gestorIOProfes;
        this.listModelFacultades = new DefaultListModel();
        this.listModelCarreras = new DefaultListModel();
        this.listModelProfesores = new DefaultListModel();
        this.listModelCursos = new DefaultListModel();

        //Muestra el listado de facultades en un jList.
        tamLista = this.listManager.getListaFacultades().size();
        for (i = 0; i < tamLista; i++)
        {   this.listModelFacultades.addElement(this.listManager.getListaFacultades().get(i));
        }
        //Muestra el listado de profesores en un jList
        tamLista = this.listManager.getListaProfesores().size();
        for (i = 0; i < tamLista; i++)
        {   this.listModelProfesores.addElement(this.listManager.getListaProfesores().get(i));
        }
        //Muestra el listado de cursos en un jList
        tamLista = this.listManager.getListaCursos().size();
        for (i = 0; i < tamLista; i++)
        {   this.listModelCursos.addElement(this.listManager.getListaCursos().get(i));
        }

        this.visualizadorListaProfes.setModel(this.listModelProfesores);
        this.visualizadorListaFacultades.setModel(this.listModelFacultades);
        this.visualizadorListaCarreras.setModel(this.listModelCarreras);
        this.visualizadorListaCursos.setModel(listModelCursos);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelVisualizadorGeneral = new javax.swing.JTabbedPane();
        PanelVisualizadorCarreras = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        visualizadorListaFacultades = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        visualizadorListaCarreras = new javax.swing.JList();
        botonNuevaCarrera = new javax.swing.JButton();
        botonNuevaFacultad = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        labelCarreraSeleccionada = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        cuadroInfornacionFacultad = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        cuadroInformacionCarrera = new javax.swing.JTextArea();
        jButton7 = new javax.swing.JButton();
        botonEditarFacultad = new javax.swing.JButton();
        botonEliminarFacultad = new javax.swing.JButton();
        botonEditarCarrera = new javax.swing.JButton();
        botonEliminarCarrera = new javax.swing.JButton();
        PanelVisualizadorProfesores = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        visualizadorListaProfes = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        cuadroInformacionProfes = new javax.swing.JTextArea();
        botonAgregarProfesor = new javax.swing.JButton();
        campoNombreProfesorNuevo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        campoRutProfesor = new javax.swing.JTextField();
        campoRamosQueDicta = new javax.swing.JTextField();
        campoHorasDisponibles = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        botonEditarProfesor = new javax.swing.JButton();
        botonEliminarProfesor = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        panelVisualizadorCursos = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        visualizadorListaCursos = new javax.swing.JList();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        cuadroInformacionCurso = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        botonAgregarCurso = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        barraMenu = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        menuVerManual = new javax.swing.JMenuItem();
        menuAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JRamos- Planificación horaria");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("JRamos - Planificación horaria"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        PanelVisualizadorGeneral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelVisualizadorGeneralMouseClicked(evt);
            }
        });
        PanelVisualizadorGeneral.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                PanelVisualizadorGeneralStateChanged(evt);
            }
        });

        jLabel3.setText("Facultad de: ");

        jLabel4.setText("Carrera: ");

        visualizadorListaFacultades.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        visualizadorListaFacultades.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                visualizadorListaFacultadesValueChanged(evt);
            }
        });
        visualizadorListaFacultades.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                visualizadorListaFacultadesComponentHidden(evt);
            }
        });
        jScrollPane3.setViewportView(visualizadorListaFacultades);

        visualizadorListaCarreras.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        visualizadorListaCarreras.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                visualizadorListaCarrerasValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(visualizadorListaCarreras);

        botonNuevaCarrera.setFont(new java.awt.Font("Dialog", 1, 10));
        botonNuevaCarrera.setText("Nueva carrera...");
        botonNuevaCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevaCarreraActionPerformed(evt);
            }
        });

        botonNuevaFacultad.setFont(new java.awt.Font("Dialog", 1, 10));
        botonNuevaFacultad.setText("Nueva facultad...");
        botonNuevaFacultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevaFacultadActionPerformed(evt);
            }
        });

        jLabel22.setText("Malla de carrera: ");

        labelCarreraSeleccionada.setText("Seleccione una facultad y luego una carrera...");

        cuadroInfornacionFacultad.setColumns(20);
        cuadroInfornacionFacultad.setRows(5);
        cuadroInfornacionFacultad.setText("Seleccione una facultad del listado del costado para ver su información");
        jScrollPane5.setViewportView(cuadroInfornacionFacultad);

        cuadroInformacionCarrera.setColumns(20);
        cuadroInformacionCarrera.setRows(5);
        cuadroInformacionCarrera.setText("Seleccione una carrera del listado del costado para ver su información");
        jScrollPane8.setViewportView(cuadroInformacionCarrera);

        jButton7.setFont(new java.awt.Font("Dialog", 1, 14));
        jButton7.setText("Ver Malla");

        botonEditarFacultad.setText("Editar facultad");

        botonEliminarFacultad.setText("Eliminar facultad");
        botonEliminarFacultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarFacultadActionPerformed(evt);
            }
        });

        botonEditarCarrera.setText("Editar carrera");

        botonEliminarCarrera.setText("Eliminar carrera");
        botonEliminarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarCarreraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelVisualizadorCarrerasLayout = new javax.swing.GroupLayout(PanelVisualizadorCarreras);
        PanelVisualizadorCarreras.setLayout(PanelVisualizadorCarrerasLayout);
        PanelVisualizadorCarrerasLayout.setHorizontalGroup(
            PanelVisualizadorCarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVisualizadorCarrerasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelVisualizadorCarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonNuevaFacultad)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonNuevaCarrera)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PanelVisualizadorCarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelVisualizadorCarrerasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelVisualizadorCarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelVisualizadorCarrerasLayout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(botonEditarFacultad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                                .addComponent(botonEliminarFacultad)
                                .addGap(82, 82, 82))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelVisualizadorCarrerasLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(PanelVisualizadorCarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelVisualizadorCarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelVisualizadorCarrerasLayout.createSequentialGroup()
                                            .addComponent(jLabel22)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(PanelVisualizadorCarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(labelCarreraSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap(38, Short.MAX_VALUE))))
                    .addGroup(PanelVisualizadorCarrerasLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(botonEditarCarrera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                        .addComponent(botonEliminarCarrera)
                        .addGap(79, 79, 79))))
        );
        PanelVisualizadorCarrerasLayout.setVerticalGroup(
            PanelVisualizadorCarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVisualizadorCarrerasLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(PanelVisualizadorCarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelVisualizadorCarrerasLayout.createSequentialGroup()
                        .addComponent(botonNuevaFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelVisualizadorCarrerasLayout.createSequentialGroup()
                        .addGroup(PanelVisualizadorCarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonEditarFacultad)
                            .addComponent(botonEliminarFacultad))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(PanelVisualizadorCarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelVisualizadorCarrerasLayout.createSequentialGroup()
                        .addGroup(PanelVisualizadorCarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCarreraSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelVisualizadorCarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonEditarCarrera)
                            .addComponent(botonEliminarCarrera)))
                    .addGroup(PanelVisualizadorCarrerasLayout.createSequentialGroup()
                        .addComponent(botonNuevaCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );

        PanelVisualizadorGeneral.addTab("Carreras", PanelVisualizadorCarreras);

        visualizadorListaProfes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        visualizadorListaProfes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                visualizadorListaProfesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(visualizadorListaProfes);

        cuadroInformacionProfes.setColumns(20);
        cuadroInformacionProfes.setRows(5);
        cuadroInformacionProfes.setText("Seleccione un profesor del listado del costado para ver su información");
        jScrollPane2.setViewportView(cuadroInformacionProfes);

        botonAgregarProfesor.setText("Agregar profesor");
        botonAgregarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarProfesorActionPerformed(evt);
            }
        });

        jLabel5.setText("Nombre Profesor:");

        jLabel6.setText("RUT:");

        jLabel7.setText("Ramos que puede dictar:");

        jLabel8.setText("Horas disponibles:");

        campoHorasDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoHorasDisponiblesActionPerformed(evt);
            }
        });

        jLabel9.setText("ej: Alberto Ceballos");

        jLabel10.setText("ej: 1234567");

        jLabel11.setText("ej: codRamo1 codRamo2");

        jLabel12.setText("ej: L4 L5 W3 W4 V1 V2");

        jLabel20.setText("Listado de profesores");

        botonEditarProfesor.setText("Editar profesor");

        botonEliminarProfesor.setText("Eliminar profesor");
        botonEliminarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarProfesorActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel14.setText("Agregar un nuevo profesor al registro: ");

        jButton5.setText("Ver su horario");

        javax.swing.GroupLayout PanelVisualizadorProfesoresLayout = new javax.swing.GroupLayout(PanelVisualizadorProfesores);
        PanelVisualizadorProfesores.setLayout(PanelVisualizadorProfesoresLayout);
        PanelVisualizadorProfesoresLayout.setHorizontalGroup(
            PanelVisualizadorProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVisualizadorProfesoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelVisualizadorProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PanelVisualizadorProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelVisualizadorProfesoresLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(botonAgregarProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelVisualizadorProfesoresLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelVisualizadorProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelVisualizadorProfesoresLayout.createSequentialGroup()
                                .addGroup(PanelVisualizadorProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelVisualizadorProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoRutProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                    .addComponent(campoNombreProfesorNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                    .addComponent(campoRamosQueDicta, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                    .addComponent(campoHorasDisponibles, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelVisualizadorProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(29, 29, 29))
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelVisualizadorProfesoresLayout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonEditarProfesor)
                                .addGap(44, 44, 44)
                                .addComponent(botonEliminarProfesor)
                                .addGap(88, 88, 88)))))
                .addContainerGap())
        );
        PanelVisualizadorProfesoresLayout.setVerticalGroup(
            PanelVisualizadorProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVisualizadorProfesoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelVisualizadorProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(botonEditarProfesor)
                    .addComponent(jButton5)
                    .addComponent(botonEliminarProfesor))
                .addGroup(PanelVisualizadorProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelVisualizadorProfesoresLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addGap(9, 9, 9)
                        .addGroup(PanelVisualizadorProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5)
                            .addComponent(campoNombreProfesorNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelVisualizadorProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6)
                            .addComponent(campoRutProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelVisualizadorProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel7)
                            .addComponent(campoRamosQueDicta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelVisualizadorProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(campoHorasDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonAgregarProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelVisualizadorProfesoresLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)))
                .addContainerGap())
        );

        PanelVisualizadorGeneral.addTab("Profesores", PanelVisualizadorProfesores);

        panelVisualizadorCursos.setMinimumSize(new java.awt.Dimension(750, 500));
        panelVisualizadorCursos.setPreferredSize(new java.awt.Dimension(780, 456));
        panelVisualizadorCursos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                panelVisualizadorCursosFocusGained(evt);
            }
        });

        visualizadorListaCursos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        visualizadorListaCursos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                visualizadorListaCursosValueChanged(evt);
            }
        });
        jScrollPane6.setViewportView(visualizadorListaCursos);

        jLabel13.setText("Listado de cursos");

        cuadroInformacionCurso.setColumns(20);
        cuadroInformacionCurso.setRows(5);
        cuadroInformacionCurso.setText("Seleccione un curso del listado del costado para ver su información");
        jScrollPane7.setViewportView(cuadroInformacionCurso);

        jLabel15.setText("Nombre del curso:");

        jLabel16.setText("Código del curso:");

        jLabel18.setText("Sección:");

        jLabel19.setText("Carreras en que se dicta:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        botonAgregarCurso.setText("Agregar Curso");
        botonAgregarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarCursoActionPerformed(evt);
            }
        });

        jButton3.setText("Editar curso");

        jButton4.setText("Eliminar curso");

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel21.setText("Agregar un nuevo curso al registro:");

        jButton6.setText("Ver su horario");

        javax.swing.GroupLayout panelVisualizadorCursosLayout = new javax.swing.GroupLayout(panelVisualizadorCursos);
        panelVisualizadorCursos.setLayout(panelVisualizadorCursosLayout);
        panelVisualizadorCursosLayout.setHorizontalGroup(
            panelVisualizadorCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVisualizadorCursosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVisualizadorCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelVisualizadorCursosLayout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelVisualizadorCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelVisualizadorCursosLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelVisualizadorCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelVisualizadorCursosLayout.createSequentialGroup()
                                        .addGroup(panelVisualizadorCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel19))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(panelVisualizadorCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField7)
                                            .addComponent(jTextField6)
                                            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(panelVisualizadorCursosLayout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(botonAgregarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(panelVisualizadorCursosLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jButton4)
                        .addGap(112, 112, 112))))
        );
        panelVisualizadorCursosLayout.setVerticalGroup(
            panelVisualizadorCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVisualizadorCursosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVisualizadorCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jButton6)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGroup(panelVisualizadorCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelVisualizadorCursosLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelVisualizadorCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelVisualizadorCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelVisualizadorCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelVisualizadorCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonAgregarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelVisualizadorCursosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        PanelVisualizadorGeneral.addTab("Cursos", panelVisualizadorCursos);

        barraMenu.setMinimumSize(new java.awt.Dimension(760, 4));

        menuArchivo.setText("Archivo");

        jMenuItem1.setText("Cargar archivo de profesores");
        menuArchivo.add(jMenuItem1);

        jMenuItem2.setText("Cargar archivo de cursos/carreras");
        menuArchivo.add(jMenuItem2);

        jMenuItem3.setText("Salir");
        menuArchivo.add(jMenuItem3);

        barraMenu.add(menuArchivo);

        menuAyuda.setText("Ayuda");

        menuVerManual.setText("Ver Manual de usuario");
        menuVerManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVerManualActionPerformed(evt);
            }
        });
        menuAyuda.add(menuVerManual);

        menuAcercaDe.setText("Acerca de...");
        menuAyuda.add(menuAcercaDe);

        barraMenu.add(menuAyuda);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelVisualizadorGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(PanelVisualizadorGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarProfesorActionPerformed
        // Acción a realizar cuando se presiona el boton "agregar profesor"
        int rut = 0, i, tamLista, posicionBarra;;
        ArrayList<Hora> listaHorasDisponibles = new ArrayList();
        ArrayList<Integer> listaCodCursosDisponibles = new ArrayList();
        if (this.campoNombreProfesorNuevo.getText().trim().equals(""))
        {       //abro nueva ventana
                DialogoError dialogoError = new DialogoError(this, rootPaneCheckingEnabled, "No hay un nombre de profesor escrito", "Debe escribir un nombre de profesor");
                dialogoError.setVisible(true);
                dialogoError = null;
                return ;
        }

        //Compruebo si el rut es válido
        try
        {       rut = Integer.valueOf(this.campoRutProfesor.getText());
                if ((rut < 1000000) || (rut > 50000000))
                    throw new NumberFormatException();
        }
        catch (NumberFormatException NFE)
        {       DialogoError dialogoError = new DialogoError(this, rootPaneCheckingEnabled, "El rut introducido no es válido", "vuelva a escribir el rut del profesor");
                dialogoError.setVisible(true);
                dialogoError = null;
                return ;
        }

        //Transformo el string con los cursos que puede dictar a un ArrayList de Integer
        try
        {       int codCurso;
                String codCursosDisp = this.campoRamosQueDicta.getText();
                if (codCursosDisp.length() != 0) //Seteo los codigos de curso que puede impartir
                        {       for (i = 0; codCursosDisp.indexOf(" ") != -1;i++)
                                {       System.out.println(codCursosDisp.substring(0, codCursosDisp.indexOf(" ")));
                                        codCurso = Integer.valueOf(codCursosDisp.substring(0, codCursosDisp.indexOf(" ")));
                                        posicionBarra = codCursosDisp.indexOf(" ");
                                        codCursosDisp = codCursosDisp.substring(posicionBarra+1);
                                        listaCodCursosDisponibles.add(new Integer(Integer.valueOf(codCurso)));
                                }
                                //Agrego el ultimo que no fue agregado en el bucle:
                                listaCodCursosDisponibles.add(new Integer(Integer.valueOf(codCursosDisp)));
                        }
        }
        catch (NumberFormatException NFE)
        {       DialogoError dialogoError = new DialogoError(this, rootPaneCheckingEnabled, "Los codigos de curso introducidos no son válidos", "vuelva a escribir los cursos disponibles del profesor");
                dialogoError.setVisible(true);
                dialogoError = null;
                return ;
        }//modifica esto!!!

        //Transformo el string de horas a un ArrayList de Hora
        try
        {       String horasDisp = this.campoHorasDisponibles.getText();
                Hora objHora;
                if (horasDisp.length() != 0)
                        {       for (i = 0; horasDisp.indexOf(" ") != -1;i++)
                                {       System.out.println(horasDisp.substring(0, horasDisp.indexOf(" ")));
                                        objHora = new Hora(horasDisp.substring(0, horasDisp.indexOf(" ")));
                                        posicionBarra = horasDisp.indexOf(" ");
                                        horasDisp = horasDisp.substring(posicionBarra+1);
                                        listaHorasDisponibles.add(objHora);
                                }
                                //Agrego el ultimo que no fue agregado en el bucle:
                                listaHorasDisponibles.add(new Hora(horasDisp));
                        }
            
        } 
        catch (HourOutOfRangeException HOORE)
        {       DialogoError dialogoError = new DialogoError(this, rootPaneCheckingEnabled, "Las horas introducidas no son válidas.", "Revise las horas escritas y vuelva a escribirlas");
                dialogoError.setVisible(true);
                dialogoError = null;
                return ;

        }

        //Si ya existe un profesor con el mismo nombre tampoco se agrega.
        ArrayList<Profesor> listaCompletaProfesores = this.listManager.getListaProfesores();
        for (Profesor profesor : listaCompletaProfesores)
        {       if (this.campoNombreProfesorNuevo.getText().equals(profesor.getNombreProfesor()))
                {       //abro nueva ventana de error.
                        DialogoError dialogoError = new DialogoError(this, rootPaneCheckingEnabled, "El nombre del profesor ya existe.", "vuelva a escribir otro nombre para el profesor");
                        dialogoError.setVisible(true);
                        dialogoError = null;
                        return ;
                }
        }
        this.listManager.agregaProfesor(this.campoNombreProfesorNuevo.getText(), rut, listaCodCursosDisponibles, listaHorasDisponibles);
        this.listModelProfesores = new DefaultListModel();
        tamLista = this.listManager.getListaProfesores().size();
        for (i = 0; i < tamLista; i++)
        {   this.listModelProfesores.addElement(this.listManager.getListaProfesores().get(i));
        }
        this.visualizadorListaProfes.setModel(this.listModelProfesores);
        this.visualizadorListaProfesValueChanged(null);

    }//GEN-LAST:event_botonAgregarProfesorActionPerformed

    private void campoHorasDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoHorasDisponiblesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoHorasDisponiblesActionPerformed

    private void botonAgregarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAgregarCursoActionPerformed

    private void menuVerManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVerManualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuVerManualActionPerformed

    private void botonNuevaCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevaCarreraActionPerformed
        //Acción a realizar cuando se presiona el boton "nueva carrera"
        DialogoCarreraNueva dialogoCarreraNueva = new DialogoCarreraNueva(this, rootPaneCheckingEnabled, listManager);
        dialogoCarreraNueva.setVisible(true);
        dialogoCarreraNueva = null;
    }//GEN-LAST:event_botonNuevaCarreraActionPerformed

    public void actualizaJListListaProfes()
    {       this.listModelProfesores = null;
            this.listModelProfesores = new DefaultListModel();
            for (Profesor profesor : this.listManager.getListaProfesores())
            {       this.listModelProfesores.addElement(profesor);
            }
            this.visualizadorListaProfes.setModel(this.listModelProfesores);
            this.visualizadorListaProfesValueChanged(null);
    }

    public void borrarProfesor(Profesor profesorABorrar)
    {       //Borro el profesor del manipulador de listas, del Jlist y del visualizador
            this.cuadroInformacionProfes.setText("Se ha eliminado correctamente el profesor "+ profesorABorrar.getNombreProfesor());
            this.listManager.eliminaProfesor(profesorABorrar);
            this.actualizaJListListaProfes();
    }
    public void borrarCarrera(Carrera carreraABorrar)
    {       //Borro la carrera del manipulador de listas, del Jlist y del visualizador
            this.cuadroInformacionCarrera.setText("Se ha eliminado correctamente la carrera de "+ carreraABorrar.getNombreCarrera()+"\nSe han eliminado también los semestres de esas carreras");
            this.listManager.eliminaCarrera(carreraABorrar.getCodigoCarrera());
            this.actualizaJListListaCarreras();
    }
    public void borrarFacultad(Facultad facultadABorrar)
    {       //Borro la facultad del manipulador de listas, del Jlist y del visualizador
            this.cuadroInfornacionFacultad.setText("Se ha eliminado correctamente la facultad de "+ facultadABorrar.getNombreFacultad()+"\nSe ha borrado ademas las carreras de esa facultad: \n"+facultadABorrar.getNombreCarreras()+"\nY se han eliminado los semestres de las carreras eliminadas\n");
            this.listManager.eliminaFacultad(facultadABorrar);
            this.actualizaJListListaFacultades();
            this.actualizaJListListaCarreras();
    }
    public void borrarCurso(Curso cursoABorrar)
    {       //Borro el curso del manipulador de listas, del Jlist y del visualizador

    }

    public void actualizaJListListaCursos()
    {       this.listModelCursos = null;
            this.listModelCursos = new DefaultListModel();
            for (Curso curso : this.listManager.getListaCursos())
            {       this.listModelCursos.addElement(curso);
            }
            this.visualizadorListaCursos.setModel(this.listModelCursos);
            visualizadorListaCursosValueChanged(null);
    }

    public void actualizaJListListaFacultades()
    {       this.listModelFacultades = null;
            this.listModelFacultades = new DefaultListModel();
            for (Facultad facultad : this.listManager.getListaFacultades())
            {       this.listModelFacultades.addElement(facultad);
            }
            this.visualizadorListaFacultades.setModel(this.listModelFacultades);
            visualizadorListaFacultadesValueChanged(null);
    }

    public void actualizaJListListaCarreras()
    {       visualizadorListaFacultadesValueChanged(null);
            visualizadorListaCarrerasValueChanged(null);
    }

    private void botonNuevaFacultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevaFacultadActionPerformed
        //Acción a realizar cuando se presiona el boton "nueva facultad"
        DialogoFacultadNueva dialogoFacultadNueva = new DialogoFacultadNueva(this, rootPaneCheckingEnabled, listManager);
        dialogoFacultadNueva.setVisible(true);
        dialogoFacultadNueva = null;
    }//GEN-LAST:event_botonNuevaFacultadActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        //Antes de escribir, debo setear los nuevos valores de los id despues de utilizar las clases
        try
        {       // Aqui se escriben las listas modificadas en los archivos.
                gestorIOCursos.escribeSemestres(listManager.getListaSemestres(), Curso.getIdCursoGlobal(), Carrera.getCodigoCarreraGlobal(), Semestre.getIdSemestreGlobal(), Facultad.getIdFacultadGlobal());
                gestorIOCursos.escribeCarreras(listManager.getListaCarreras(), Curso.getIdCursoGlobal(), Carrera.getCodigoCarreraGlobal(), Semestre.getIdSemestreGlobal(), Facultad.getIdFacultadGlobal());
                gestorIOCursos.escribeCursos(listManager.getListaCursos(), Curso.getIdCursoGlobal(), Carrera.getCodigoCarreraGlobal(), Semestre.getIdSemestreGlobal(), Facultad.getIdFacultadGlobal());
                gestorIOCursos.escribeFacultades(listManager.getListaFacultades(), Curso.getIdCursoGlobal(), Carrera.getCodigoCarreraGlobal(), Semestre.getIdSemestreGlobal(), Facultad.getIdFacultadGlobal());
                gestorIOProfes.escribeProfes(listManager.getListaProfesores(), Profesor.getIdProfesorGlobal());
        }
        catch (Exception e)
        {       System.out.println("Error al escribir en los archivos");
        }
    }//GEN-LAST:event_formWindowClosing

    private void visualizadorListaFacultadesComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_visualizadorListaFacultadesComponentHidden

    }//GEN-LAST:event_visualizadorListaFacultadesComponentHidden

    private void visualizadorListaFacultadesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_visualizadorListaFacultadesValueChanged
        // Acción a realizar cuando se selecciona una facultad, se debe mostrar en el jList solo las carreras de esa facultad
        int tamLista, i;
        Facultad facultadSeleccionada;
        ArrayList<Carrera> listaCarrerasFacultadSeleccionada = null;
        this.listModelCarreras = null;
        this.listModelCarreras = new DefaultListModel();
        facultadSeleccionada = (Facultad)this.visualizadorListaFacultades.getSelectedValue();
        if (facultadSeleccionada != null)
        {       listaCarrerasFacultadSeleccionada = facultadSeleccionada.getCarreras();
                tamLista = listaCarrerasFacultadSeleccionada.size();
                for (i = 0; i < tamLista; i++)
                {       this.listModelCarreras.addElement(listaCarrerasFacultadSeleccionada.get(i));
                }
                //Muestro la información de la facultad seleccionada en el cuadro de informacion
                this.cuadroInfornacionFacultad.setText("Facultad de " +facultadSeleccionada.getNombreFacultad()+ "\nDetalles: \n" + facultadSeleccionada.getDescripcion());
        }
        this.visualizadorListaCarreras.setModel(this.listModelCarreras);
        this.cuadroInformacionCarrera.setText("Seleccione una carrera del listado del costado para ver su información");
    }//GEN-LAST:event_visualizadorListaFacultadesValueChanged

    private void visualizadorListaCarrerasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_visualizadorListaCarrerasValueChanged
        // Acción a realizar cuando se selecciona un elemento de la lista de carreras
        //Se debe mostrar el nombre de carrera en "labelCarreraSeleccionada"
        //Acá se muestra el nombre de la carrera seleccionada en el jlabel "labelCarreraSeleccionada"
        Carrera carreraSeleccionada;
        carreraSeleccionada = (Carrera)this.visualizadorListaCarreras.getSelectedValue();
        if (carreraSeleccionada != null)
        {       labelCarreraSeleccionada.setText(carreraSeleccionada.getNombreCarrera());
                this.cuadroInformacionCarrera.setText("Nombre de Carrera: " + carreraSeleccionada.getNombreCarrera()+"\nFacultad de "+carreraSeleccionada.getFacultad()+"\nCantidad de semestres : "+carreraSeleccionada.getListaSemestres().size()+"\nDescripción de la carrera: "+carreraSeleccionada.getDescripcion());
        }
        else
                this.cuadroInformacionCarrera.setText("Seleccione una carrera del listado del costado para ver su información");
    }//GEN-LAST:event_visualizadorListaCarrerasValueChanged

    private void visualizadorListaProfesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_visualizadorListaProfesValueChanged
        //Acá se muestra la información del profesor seleccionado
        Profesor profesorSeleccionado;
        profesorSeleccionado = (Profesor)this.visualizadorListaProfes.getSelectedValue();
        if (profesorSeleccionado != null)
        {       this.cuadroInformacionProfes.setText("Nombre del profesor: "+profesorSeleccionado.getNombreProfesor()+"\nRut del profesor: "+profesorSeleccionado.getRutProfesor()+"\nCursos para impartir: "+profesorSeleccionado.getCodCursosQueImparte()+"\nHoras disponibles: "+profesorSeleccionado.getHorasDisponibles() + "\nCursosAsignados: "+profesorSeleccionado.getCursosAsignados()+"\nHoras asignadas: "+profesorSeleccionado.getHorasAsignadas());
        }
        else
                this.cuadroInformacionProfes.setText("Seleccione un profesor del listado del costado para ver su información");
    }//GEN-LAST:event_visualizadorListaProfesValueChanged

    private void botonEliminarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarProfesorActionPerformed
        // Acción a realizar cuando se presiona el boton "eliminar profesor"
        // Se revisa cual es el profesor seleccionado en la JList de profesores y es ese el que se va a eliminar.
        // Se lanza una ventana pidiendo confirmación a esta acción
        Profesor profesorSeleccionado;
        profesorSeleccionado = (Profesor)this.visualizadorListaProfes.getSelectedValue();
        if (profesorSeleccionado != null)
        {       //Lanzo un dialogo pidiendo confirmación para eliminar el profesor seleccionado
                DialogoConfirmacion dialogoConfirmacion = new DialogoConfirmacion(this, rootPaneCheckingEnabled, DialogoConfirmacion.BORRA_PROFESOR, profesorSeleccionado);
                dialogoConfirmacion.setVisible(true);
                dialogoConfirmacion = null; 
                return ;
        }
        else
        {       //abro nueva ventana de error.
                DialogoError dialogoError = new DialogoError(this, rootPaneCheckingEnabled, "No ha seleccionado un profesor para eliminar", "Seleccione un profesor desde la lista de profesores del costado");
                dialogoError.setVisible(true);
                dialogoError = null;
                return ;
        }
    }//GEN-LAST:event_botonEliminarProfesorActionPerformed

    private void botonEliminarFacultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarFacultadActionPerformed
        // Acción a realizar cuando se presiona el boton "eliminar facultad"
        // Se revisa cual es la facultad seleccionada en la JList de facultades y es ese el que se va a eliminar.
        // Se lanza una ventana pidiendo confirmación a esta acción
        Facultad facultadSeleccionada;
        facultadSeleccionada = (Facultad)this.visualizadorListaFacultades.getSelectedValue();
        if (facultadSeleccionada != null)
        {       //Lanzo un dialogo pidiendo confirmación para eliminar la facultad seleccionada
                DialogoConfirmacion dialogoConfirmacion = new DialogoConfirmacion(this, rootPaneCheckingEnabled, DialogoConfirmacion.BORRA_FACULTAD, facultadSeleccionada);
                dialogoConfirmacion.setVisible(true);
                dialogoConfirmacion = null;

                return ;
        }
        else
        {       //abro ventana de error.
                DialogoError dialogoError = new DialogoError(this, rootPaneCheckingEnabled, "No ha seleccionado una facultad para eliminar", "Seleccione una facultad desde la lista de facultades del costado");
                dialogoError.setVisible(true);
                dialogoError = null;
                return ;
        }
    }//GEN-LAST:event_botonEliminarFacultadActionPerformed

    private void botonEliminarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarCarreraActionPerformed
        // Acción a realizar cuando se presiona el boton "eliminar carrera"
        // Se revisa cual es la carrera seleccionada en la JList de carreras y es ese el que se va a eliminar.
        // Se lanza una ventana pidiendo confirmación a esta acción
        Carrera carreraSeleccionada;
        carreraSeleccionada = (Carrera)this.visualizadorListaCarreras.getSelectedValue();
        if (carreraSeleccionada != null)
        {       //Lanzo un dialogo pidiendo confirmación para eliminar la facultad seleccionada
                DialogoConfirmacion dialogoConfirmacion = new DialogoConfirmacion(this, rootPaneCheckingEnabled, DialogoConfirmacion.BORRA_CARRERA, carreraSeleccionada);
                dialogoConfirmacion.setVisible(true);
                dialogoConfirmacion = null;

                return ;
        }
        else
        {       //abro ventana de error.
                DialogoError dialogoError = new DialogoError(this, rootPaneCheckingEnabled, "No ha seleccionado una carrera para eliminar", "Seleccione una carrera desde la lista de carreras del costado");
                dialogoError.setVisible(true);
                dialogoError = null;
                return ;
        }
    }//GEN-LAST:event_botonEliminarCarreraActionPerformed

    private void visualizadorListaCursosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_visualizadorListaCursosValueChanged
        //Acá se muestra la información del curso seleccionado
        //Acá se muestra el nombre de la carrera seleccionada en el jlabel "labelCarreraSeleccionada"
        Curso cursoSeleccionado;
        String horarioConSalas;
        cursoSeleccionado = (Curso)this.visualizadorListaCursos.getSelectedValue();
        if (cursoSeleccionado != null)
        {       horarioConSalas = "L5-L6(546), M3-M4(546), J1-J2(546)"; //Es un ejemplo, debe ser implementado
                this.cuadroInformacionCurso.setText("Nombre del curso: " + cursoSeleccionado.getNombreCurso()+"\nCódigo del curso: "+cursoSeleccionado.getCodigoCurso()+"\nSección: "+cursoSeleccionado.getSeccion()+"\nProfesor asignado: "+cursoSeleccionado.getNombreProfesor()+"\nCarreras en que se dicta: "+cursoSeleccionado.getEnCarreras()+"\nHorario: "+horarioConSalas+"\nDescripción del curso: "+cursoSeleccionado.getDescripcion());
        }
        else
                this.cuadroInformacionCurso.setText("Seleccione una carrera del listado del costado para ver su información");

    }//GEN-LAST:event_visualizadorListaCursosValueChanged

    private void panelVisualizadorCursosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_panelVisualizadorCursosFocusGained

    }//GEN-LAST:event_panelVisualizadorCursosFocusGained

    private void PanelVisualizadorGeneralStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_PanelVisualizadorGeneralStateChanged

    }//GEN-LAST:event_PanelVisualizadorGeneralStateChanged

    private void PanelVisualizadorGeneralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelVisualizadorGeneralMouseClicked
        // cuando cambia el tab a los cursos, redibujo la JList de cursos
        actualizaJListListaCursos();
        actualizaJListListaCarreras();
        actualizaJListListaFacultades();
        actualizaJListListaProfes();
    }//GEN-LAST:event_PanelVisualizadorGeneralMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelVisualizadorCarreras;
    private javax.swing.JTabbedPane PanelVisualizadorGeneral;
    private javax.swing.JPanel PanelVisualizadorProfesores;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton botonAgregarCurso;
    private javax.swing.JButton botonAgregarProfesor;
    private javax.swing.JButton botonEditarCarrera;
    private javax.swing.JButton botonEditarFacultad;
    private javax.swing.JButton botonEditarProfesor;
    private javax.swing.JButton botonEliminarCarrera;
    private javax.swing.JButton botonEliminarFacultad;
    private javax.swing.JButton botonEliminarProfesor;
    private javax.swing.JButton botonNuevaCarrera;
    private javax.swing.JButton botonNuevaFacultad;
    private javax.swing.JTextField campoHorasDisponibles;
    private javax.swing.JTextField campoNombreProfesorNuevo;
    private javax.swing.JTextField campoRamosQueDicta;
    private javax.swing.JTextField campoRutProfesor;
    private javax.swing.JTextArea cuadroInformacionCarrera;
    private javax.swing.JTextArea cuadroInformacionCurso;
    private javax.swing.JTextArea cuadroInformacionProfes;
    private javax.swing.JTextArea cuadroInfornacionFacultad;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel labelCarreraSeleccionada;
    private javax.swing.JMenuItem menuAcercaDe;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenuItem menuVerManual;
    private javax.swing.JPanel panelVisualizadorCursos;
    private javax.swing.JList visualizadorListaCarreras;
    private javax.swing.JList visualizadorListaCursos;
    private javax.swing.JList visualizadorListaFacultades;
    private javax.swing.JList visualizadorListaProfes;
    // End of variables declaration//GEN-END:variables

}
